name: CI / CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy bandit
      - run: flake8 .
      - run: mypy .
      - run: bandit -r .

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python -m pytest tests/ -v

  build-and-test-image:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: image-test:latest
          load: true
      - run: |
          docker run -d --name ci_test_container -p 8000:8000 image-test:latest
          for i in {1..20}; do
            if curl -sS http://localhost:8000/ >/dev/null; then
              break
            fi
            sleep 1
          done
          curl -v http://localhost:8000/ --fail
      - run: docker rm -f ci_test_container || true
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build-and-test-image
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dummyrequestcounter:latest
            ${{ secrets.DOCKER_USERNAME }}/dummyrequestcounter:${{ github.sha }}